### ISSUE TITLE
Add CI to auto build documentation

### ISSUE THREAD

**Issue by DeveloperPaul123** [DeveloperPaul123/modern-cv#3]
We should auto build the documentation for every commit and we should also upload docs to releases as well.

Starting point:

```yaml
name: Build document
on: [push, workflow_dispatch]
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Typst
        uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
          version: 'v0.11.0'
      - run: typst compile modern-cv-docs.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: modern-cv-documentation
          path: modern-cv-documentation.pdf
```

One issue may be the fonts, but I think these are (mostly) available on `chocolatey`.
